### ISSUE TITLE
`TypeError: sendToWormhole is not a function` after upgrading to v2.0.1 using CommonJS require

### ISSUE THREAD

**Issue by lvboda** [node-modules/stream-wormhole#9]
This issue appears to be caused by a breaking change in the way the module is exported in v2.0.0. It seems that CommonJS require() no longer returns the function directly.

``` js
const sendToWormhole = require('stream-wormhole');
await sendToWormhole(stream);

// v1.1.0 ✅
// update to v2.0.1 ❌
// nodejs.TypeError: sendToWormhole is not a function
```

**Comment by fengmk2** [comment]
Should change to export style:

```js
const { sendToWormhole } = require('stream-wormhole');
```

`export default` not work on commonjs.
